sudo: required

language: python

services:
  - docker

before_install:
  - docker pull slycat/slycat-developer
  - docker run -p 2222:22 -p 80:80 -p 443:443 -p 5984:5984 -d --name slycat slycat/slycat-developer
  - docker exec -i slycat bash -c "cd /home/slycat/src/slycat; git pull"
  - docker exec -i slycat bash -c "sudo service sylcat-web-server restart"
  - docker exec -i slycat bash -c "cd /home/slycat; wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz"
  - docker exec -i slycat bash -c "cd /home/slycat; tar xf geckodriver-v0.11.1-linux64.tar.gz"
  - docker exec -i slycat bash -c "cd /home/slycat; cp geckodriver /usr/bin/geckodriver"
  - docker exec -i slycat bash -c "cd /home/slycat; mv geckodriver /usr/bin/wires"
  - docker exec -i slycat bash -c "cd /home/slycat; export PATH=/usr/bin:$PATH"
  - docker exec -i slycat bash -c "cd; export PATH=/home/slycat/install/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;export PYTHONPATH=/home/slycat/src/slycat/packages; behave -i \"(agent|hyperchunks|rest-api|slycat-web-server|slycat-project)\" /home/slycat/src/slycat/features/"
