language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - sudo apt-get update -qq
#  - sudo apt-get install -y python-gtk2 wget
  - env | sort
  - ls -l
  - cd $TRAVIS_BUILD_DIR
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - mkdir ffmpeg
  - tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg
  - export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/packages:$PYTHONPATH

install:
  - pip install behave cherrypy==3.2.6 coverage coveralls ldap mock numpy paramiko Pillow pyparsing>=2.0.3 requests scipy tornado-couchdb
script:
  - coverage run --source slycat -m behave -i "(agent|hyperchunks|rest-api)"
  - coverage report
after_script:
  - coveralls
