language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc gfortran g++ python2.7-dev libldap2-dev libsasl2-dev liblapack-dev haproxy ssh
  - env | sort
  - ls -l
  - cd $TRAVIS_BUILD_DIR
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - mkdir ffmpeg
  - tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg
  - export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/packages:$PYTHONPATH
install:
#  - pip install behave "cherrypy==3.2.6" coverage coveralls python-ldap mock nose numpy paramiko Pillow "pyparsing>=2.0.3" requests scipy tornado-couchdb
  - pip install behave "cherrypy==3.2.6" couchdb coverage coveralls python-ldap mock nose numpy paramiko Pillow "pyparsing>=2.0.3" requests tornado-couchdb
  - python $TRAVIS_BUILD_DIR/web-server/slycat-couchdb-setup.py
script:
  - python $TRAVIS_BUILD_DIR/feed-server/slycat-feed-server.py --config $TRAVIS_BUILD_DIR/docker/slycat-demo/config.ini &
  - python $TRAVIS_BUILD_DIR/web-server/slycat-web-server.py --config $TRAVIS_BUILD_DIR/docker/slycat-demo/config.ini &
  - coverage run --source slycat -m behave -i "(agent|hyperchunks|rest-api)"
  - coverage report
after_script:
  - coveralls
